### ISSUE TITLE
Mocked platforms timeout on tests

### ISSUE THREAD

**Issue by BlackstoneEngineering** [ARMmbed/mbed-ls#100]
## Problem
I tried to mock the hexiwear device by doing `mbedls --mock=0214:HEXIWEAR`, this allowed me to then run `singletest.py -j 0 --tc GCC_ARM -V`, but all tests time out. I then instead went and modified mbedls, adding the appropriate line to mbedls to enable hexiwear, re-installed, deleted the build directory, and re-ran the tests. Then all tests worked. 

## Conclusion
Something in the `mock` subcommand doesnt work with tests. Not sure what

## Solution
make mock work with testing infrastructure as this is the primary way we expect users to test their platforms before submitting a PR.

**Comment by BlackstoneEngineering** [comment]
Testing on mbedmicro/mbed

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2740

**Comment by PrzemekWirkus** [comment]
@BlackstoneEngineering Austin did you take under consideration that `--mock` works only in the same directory not globally. Description is in [this](https://github.com/ARMmbed/mbed-ls#mocking-example-with-freescale-k64f-platform) chapter in the description under third block.

I quote: **"We can observe changes immediately. Please note this change only works in the same directory because we save .mbedls-mock file locally:"**.

Please try with pre HEX mbed-ls and this workflow:
```
$ cd mbed
$ cd workspace_tools
$ mbedls --mock=0214:HEXIWEAR
$ singletest.py --auto --tc GCC_ARM -V
```

I was unsure if command you've put here (`singletest.py -j 0 --tc GCC_ARM -V) is exactly what you were using.

I'm assuming that you were actually using `--auto` to detect HEX platform and forced `GCC_ARM` toolchain using `--tc` command line switch.

**Comment by BlackstoneEngineering** [comment]
Yes, i took the local folder into consideration. I even had @bridadan double check to make sure I wasn't crazy. Using `--mock` worked in so far as identifying the board correctly, but did not work when trying to run the test suite (singletest.py), however when I modified mbed-ls-git and reinstalled the test suite worked correctly.

This is going to be a terrible usability bug when we try to get people in the general populace / partners to port their stuff with minimal support.

**Comment by PrzemekWirkus** [comment]
Done via #106

**Comment by BlackstoneEngineering** [comment]
Awesome, closing issue
