### ISSUE TITLE
mbedls shows different target ID depending on lstools_base.py

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/mbed-ls#195]
We've noticed that `mbedls` shows different `target_id` depending on whether the [database](https://github.com/ARMmbed/mbed-ls/blob/master/mbed_lstools/lstools_base.py#L85) has been updated or not.

It makes sense to display a different `platform_name` (to match the database), but the `target_id` is not something that changes on the mbed interface.

For example, this is the result before updating the database (wrong):
```
$ mbedls
+---------------+----------------------+--------------------------+--------------+--------------------------+-----------------+
| platform_name | platform_name_unique | mount_point              | serial_port  | target_id                | daplink_version |
+---------------+----------------------+--------------------------+--------------+--------------------------+-----------------+
| unknown       | None[0]              | /media/marsal01/TilePlus | /dev/ttyACM0 | 066EFF535652837267241735 | 0221            |
+---------------+----------------------+--------------------------+--------------+--------------------------+-----------------+
```

This is the info shown after adding the entry to the database (correct/expected):

```
$ mbedls
+--------------------+-----------------------+--------------------------+--------------+--------------------------+-----------------+
| platform_name      | platform_name_unique  | mount_point              | serial_port  | target_id                | daplink_version |
+--------------------+-----------------------+--------------------------+--------------+--------------------------+-----------------+
| SILICA_SENSOR_NODE | SILICA_SENSOR_NODE[0] | /media/marsal01/TilePlus | /dev/ttyACM0 | 076602216D2360195267F642 | 0221            |
+--------------------+-----------------------+--------------------------+--------------+--------------------------+-----------------+
```

**Comment by bridadan** [comment]
@MarceloSalazar I can't say for sure since I don't have the board, but mbed-ls looks in a few different places for a target ID: There's the USB ID which is presented by the USB driver, but there's also the target ID contained within the `DETAILS.TXT` and `MBED.HTML` files. Most recent firmware unify all of these values, but some older ones do not. It will check the database for both of these target IDs and if it doesn't find it in there, it picks one of them to display as `unknown`.

If it happens to find the other target ID in the database, then in this case this is what's presented. I have a feeling this is what's happening here, however I can't say for sure without one of the boards.

**Comment by MarceloSalazar** [comment]
@bridadan if you want to try, there are boards in your office ;)
I think you're right, there are different IDs and the mbed-ls tool seems to look at these and generates a different output depending on whether the 'main' ID is in the database.

**Comment by theotherjimmy** [comment]
@MarceloSalazar This is expected behavoir. Closing.
